name: 'Generate contract library'
description: 'Generates NuGet package with a smart contract wrapper'
inputs:
  contract:
    description: 'Contract name'
    required: true
  funcitons:
    description: 'List of functions to include into the library'
    required: true
  events:
    description: 'List of events to include into the library'
    required: true
  version:
    description: 'The version of the release in semver format'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'