name: build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: gcc --version
      - name: Install dependencies
        run: npm install
      - name: Compile smart-contracts
        run: npx oz compile
